services:
  rdd-zhaoyan:
    image: quay.io/jupyter/pytorch-notebook:cuda12-python-3.11
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    container_name: rdd-zhaoyan
    ports:
      - "9000:8888"
